<!-- Family Service Completion Modal -->
<div class="modal fade" id="familyCompletionDetailsModal" tabindex="-1" role="dialog" aria-labelledby="familyCompletionDetailsModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header bg-success text-white">
                <h5 class="modal-title" id="familyCompletionDetailsModalLabel">
                    <i class="feather icon-check-circle mr-2"></i><?= __('family_completion_details') ?>
                </h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="familyCompletionDetailsForm">
                    <input type="hidden" id="familyCompletionBookingId" name="booking_id">
                    
                    <div class="alert alert-info">
                        <?= __('please_specify_the_documents_and_items_being_returned_to_the_family') ?>
                    </div>

                    <div class="table-responsive">
                        <table class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th><?= __('document_item') ?></th>
                                    <th class="text-center"><?= __('returned') ?></th>
                                </tr>
                            </thead>
                            <tbody id="familyCompletionDetailsTableBody">
                                <!-- Document rows will be generated by JavaScript -->
                            </tbody>
                        </table>
                    </div>

                    <div class="form-group mt-3">
                        <label for="familyCompletionAdditionalNotes"><?= __('additional_notes') ?></label>
                        <textarea class="form-control" id="familyCompletionAdditionalNotes" name="additional_notes" rows="3" 
                                 placeholder="<?= __('enter_any_additional_notes_about_the_completion') ?>"></textarea>
                    </div>

                    <div class="form-group">
                        <div class="custom-control custom-checkbox">
                            <input type="checkbox" class="custom-control-input" id="familyCompletionConfirmation" name="confirmation" required>
                            <label class="custom-control-label" for="familyCompletionConfirmation">
                                <?= __('i_confirm_all_documents_and_items_have_been_properly_returned') ?>
                            </label>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal"><?= __('cancel') ?></button>
                <button type="button" class="btn btn-success" id="familyGenerateCompletionFormBtn">
                    <i class="feather icon-file-text mr-2"></i><?= __('generate_completion_form') ?>
                </button>
            </div>
        </div>
    </div>
</div>